### ISSUE TITLE
Malfunction in the new update.

### ISSUE THREAD

**Issue by mikassio** [TheComputerGeek2/MagicSpells#26]
Hello.

When I saw a new update , I was delighted. But when I checked it in action - it did not work .

The modifier to the pass-condition: ANY
It did not work the second condition.
 
For example:
modifiers: 
name: 
checks: 
-hasitem 373 required 
-inblock 9 required
pass-condition: ANY

If it is used , it will only work with item 374 , and in the water without the subject - no.
And if you put a pass-condition: ALL, then everything works .. But it can be done with a conventional modifier :с

Fix, pls :с

**Comment by mikassio** [comment]
modifiers: 
     name: 
     checks: 
          - hasitem 373 required 
          - inblock 9 required
      pass-condition: ANY

**Comment by TheComputerGeek2** [comment]
@mikassio this is actually more about the nature of the modifier action you used. the modifier action called required will cancel the spell event itself since I allow the checks to run fully. What you would do instead would be something like the following
```yaml
modifiers:
    name:
        checks:
            - !hasitem 373 stop
            - !inblock 9 stop
        pass-condition: ANY
```

and then in your spell, you could use this
```yaml
modifiers:
    - collection name required
```

The reason why this should work differently is that the require action actually does does something other than just discontinuing the processing of further modifiers which is to cancel the event. the stop action on the other hand, only stops the processing of further modifiers but won't cancel the event. A similar situation exists with the denied action in which it will cancel the event when processing.

**Comment by mikassio** [comment]
Thank you. 

I've got one more is not clear bug. Above the blocks from nova effect floating blocks of stone.
Screenshot can be viewed here http://nisovin.com/forums/index.php?threads/help-with-nova-effect-please.2210/.

**Comment by mikassio** [comment]
Oh, no, it does not work.

> modifiers:
    name:
        checks:
            - !hasitem 373 stop
            - !inblock 9 stop
        pass-condition: ANY

**Comment by MidnightChipmunk** [comment]
Try removing the ! and when you put the collection on your spell deny it.

**Comment by TheComputerGeek2** [comment]
@mikassio @MidnightChipmunk just quote the checks, like this
```yaml
modifiers:
    name:
        checks:
            - "!hasitem 373 stop"
            - "!inblock 9 stop"
```
The reason that was causing an error is because yaml was treating it like a tag rather than a normal string.

**Comment by mikassio** [comment]
Thaaank you :)

**Comment by mikassio** [comment]
What about flying over the block of stone blocks in the nova effect, about which I wrote above?

**Comment by TheComputerGeek2** [comment]
@mikassio I'm afraid I don't understand what the issue with that spell is. Perhaps you could elaborate as to what it is supposed to do and what it is doing that is incorrect.

**Comment by mikassio** [comment]
@TheComputerGeek2 yes, is working.
