### ISSUE TITLE
More variables in MenuSpell

### ISSUE THREAD

**Issue by sudnly** [TheComputerGeek2/MagicSpells#584]
variables:
 itemtype:
  type: playerstring
  default-value: "light_gray_stained_glass_pane"
  permanent: true
 itemamount
  type: player
  default: 34
  permanent: true
 itemmodel:
  type: player
  default: 1
  permanent: true
  
a:
    spell-class: ".MenuSpell"
    options:
        Slot_1:
            slot: 0
            item: 
                type: "%var:itemtype%"
                amount: itemamount
                custom-model-data: itemmodel
                
                
This would be very very nice.

**Comment by JasperLorelai** [comment]
While Beta 11 was in locked testing, we experimented with global variable replacement, not just for your example but for almost any spell property. I believe we plan to release it in Beta 12.

The test builds, I believe, doesn't implement these changes in the Menu spell due to its complexity, but it too will get it's changes too.

We can help you locate the branch with these changes if you know how to build jars straight from the source. Otherwise you'll have to wait for the release of Beta 12 or join our Discord server where you can ask for access to test builds.
