### ISSUE TITLE
Conflict with Bedrock users

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [TheComputerGeek2/MagicSpells#862]
### Confirmation:

- [X] [My server is supported by MagicSpells.](https://github.com/TheComputerGeek2/MagicSpells/wiki/Supported-Versions)
- [X] This bug occurs on PaperMC itself, not just its forks which I might be using.

### Intended outcome:

Hi, the plugin has a problem and it doesn't let me deliver an item to a user with a special character in his nickname. Why do you control that aspect if I as server owner can allow the characters I want?

In this case Geyser adds a dot '.' to players who are Bedrock.

```
[08:51:54.130 INFO]: magicspells:magicspells magicitem bee_espada 1 .AgustinOut
[08:51:55.758 INFO]: Error: .AgustinOut is not a valid username.
```
How can I solve this problem without waiting for them to release an update? I passed all my kits to be managed by MS but now I have this problem....

### Actual outcome:

deliver the kit to the player who is a bedrock client.

### MagicSpells version:

MagicSpells version 4.0-Beta-12

### Minecraft server version:

git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### Relevant plugins:

PlaceholderAPI version 2.11.4

**Comment by JasperLorelai** [comment]
Two things currently require a vanilla username pattern:
1. `%playervar:<player>:<varName>:[precision]%` & `%playerpapi:<player>:<placeholder>%` internal MS placeholders.  Requires it because it's arguably easier to parse the placeholder but it should probably be changed.
2. Commands when specifying a username argument. Requiring it is not intended by us. It is done by a command library we use to create commands.

If you are a dev or have one working for your server, a current workaround is to have this running:
```java
@EventHandler
public void onMSLoaded(MagicSpellsLoadedEvent event) {
	MagicSpells.getCommandManager().setValidNamePredicate(string -> true);
}
```
